//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win10_BrightnessSlider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win10_BrightnessSlider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_fluent_sunny_24_rglr_outlined {
            get {
                object obj = ResourceManager.GetObject("ic_fluent_sunny_24_rglr_outlined", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sunny_black {
            get {
                object obj = ResourceManager.GetObject("sunny_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sunny_white {
            get {
                object obj = ResourceManager.GetObject("sunny_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wifi_black {
            get {
                object obj = ResourceManager.GetObject("wifi_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wifi_not_connected_black_wght700 {
            get {
                object obj = ResourceManager.GetObject("wifi_not_connected_black_wght700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wifi_not_connected_wght700 {
            get {
                object obj = ResourceManager.GetObject("wifi_not_connected_wght700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wifi_white {
            get {
                object obj = ResourceManager.GetObject("wifi_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        /// <summary>
        ///  guid doesnt generate this ?? 
        ///  what the fck!!.
        ///  i have to write this by hand... at least there was example... from vs202 17.11.
        /// </summary>
        internal static System.Drawing.Bitmap wifi_proxy_white_wght700
        {
            get
            {
                object obj = ResourceManager.GetObject("wifi_proxy_white_wght700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///  guid doesnt generate this ?? 
        ///  what the fck!!.
        ///  i have to write this by hand... at least there was example... from vs202 17.11.
        /// </summary>
        internal static System.Drawing.Bitmap wifi_proxy_black_wght700
        {
            get
            {
                object obj = ResourceManager.GetObject("wifi_proxy_black_wght700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        /// <summary>
        ///  guid doesnt generate this ?? 
        ///  what the fck!!.
        ///  i have to write this by hand... at least there was example... from vs202 17.11.
        /// </summary>
        internal static System.Drawing.Bitmap wifi_proxy__white_Filled
        {
            get
            {
                object obj = ResourceManager.GetObject("wifi_proxy-white_FILL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///  guid doesnt generate this ?? 
        ///  what the fck!!.
        ///  i have to write this by hand... at least there was example... from vs202 17.11.
        /// </summary>
        internal static System.Drawing.Bitmap wifi_proxy__black_Filled
        {
            get
            {
                object obj = ResourceManager.GetObject("wifi_proxy-black_FILL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        

    }
}
